---
name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish the site'
        type: boolean
        default: false
      theme_version:
        description: 'The version of the theme to use'
        type: string
        default: 'master'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-caller
  cancel-in-progress: true

jobs:
  call_build:
    uses: reenignearcher/beautiful-jekyll/.github/workflows/ci.yml@master
    with:
      publish: ${{
          (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
          github.event.inputs.publish == 'true' ||
          'false'
        }}
      theme_version: ${{ github.event.inputs.theme_version || 'master' }}
